default_platform :ios

WORKSPACE="YOUR_WORKSPACE.xcworkspace"
DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=10.3"
CONFIGURATION="Debug"

XCFIT_SCHEME="YOUR_TARGET_ProtocolBDDTests"
XCFIT_CUCUMBERISH_SCHEME="YOUR_TARGET_CucumberTests"
XCFIT_FITNESSE_SCHEME="AcceptanceUnitTests"

desc "Runs XCFit Protocol Oriented or Page Object Tests and Generate JUnit and HTML reports"
lane :xcfit do |options|
  opts = {
    :scheme => XCFIT_SCHEME,
    :workspace => WORKSPACE,
    :configuration => CONFIGURATION,
    :destination => DESTINATION,
    :buildlog_path => './build',
    :output_directory => './build/xcfit/reports',
    :output_style => 'basic',
    :output_types => 'junit, html',
    :code_coverage => true,
  }
  scan(opts)
end

# desc "Runs XCFit Cucumberish Tests and Generate JUnit and HTML reports"
# lane :xcfit_cucumberish do |options|
#   opts = {
#     :scheme => XCFIT_CUCUMBERISH_SCHEME,
#     :workspace => WORKSPACE,
#     :configuration => CONFIGURATION,
#     :destination => DESTINATION,
#     :buildlog_path => './build',
#     :output_directory => './build/cucumberish/reports',
#     :output_style => 'basic',
#     :output_types => 'junit, html',
#     :code_coverage => true,
#   }
#   scan(opts)
# end
# 
# desc "Runs XCFit Fitnesse Tests and Generate JUnit and HTML reports"
# lane :xcfit_fitnesse do |options|
#   opts = {
#     :scheme => XCFIT_FITNESSE_SCHEME,
#     :workspace => WORKSPACE,
#     :configuration => CONFIGURATION,
#     :destination => DESTINATION,
#     :buildlog_path => './build',
#     :output_directory => './build/fitnesse/reports',
#     :output_style => 'basic',
#     :output_types => 'junit, html',
#     :code_coverage => true,
#   }
#   scan(opts)
# end
