use_frameworks!

# Replace the values with your targets for the CocoaPods.
# Also Comment the targets you are no longer using in the project.

PROTOCOL_BDD_TARGET = "YOUR_APP_ProtocolBDDTests"
PAGE_OBJECT_TEST_TARGET = "YOUR_APP_PageObjectTests"
CUCUMBER_TEST_TARGET = "YOUR_APP_CucumberTests"
FITNESSE_ACCEPTANCE_TEST_TARGET = "AcceptanceTests"
FITNESSE_ACCEPTANCE_XCTEST_TARGET = "AcceptanceUnitTests"

target PROTOCOL_BDD_TARGET do
    pod 'XCFit'
end

# target PAGE_OBJECT_TEST_TARGET do
#     pod 'XCFit'
# end
#
# target CUCUMBER_TEST_TARGET do
#   pod 'Cucumberish'
# end
#
# target FITNESSE_ACCEPTANCE_TEST_TARGET do
#     pod 'OCSlimProject'
# end
#
# target FITNESSE_ACCEPTANCE_XCTEST_TARGET do
#     pod 'OCSlimProjectTestBundleSupport'
# end
